# Site settings
title:       Tuple
email:       tulakan.r@gmail.com 
author:      tuple team
description: "Blog about technology, prgramming and a bit of music and travelling"
baseurl:     ""
url:         "http://tupleblog.github.io/" 

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: 	true
github_username:	tupleblog
twitter_username:	
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     5
sass:
  compressed: true
